const { MenuList } = require('./src/index');
const fs = require('fs');
const path = require('path');

const menuData = async () => {
await MenuList.bulkCreate([
    {
      menuId: 1,
      menuName: '샐러드',
      menuCalorie: 1.2,
      menuImage: fs.readFileSync(path.join(__dirname, 'images', '1 샐러드.jpg')).toString('base64'),
      menuCarbo: 0.05,
      menuProtein: 0.01,
      menuFat: 0.1,
    },
    {
      menuId: 2,
      menuName: '닭가슴살',
      menuCalorie: 1.1,
      menuImage: fs.readFileSync(path.join(__dirname, 'images', '2 닭가슴살.jpg')).toString('base64'),
      menuCarbo: 0,
      menuProtein: 0.23,
      menuFat: 0.012,
    },
    {
        menuId: 3,
        menuName: '짜장면',
        menuCalorie: 1.9,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '3 짜장면.jpg')).toString('base64'),
        menuCarbo: 0.257,
        menuProtein: 0.06,
        menuFat: 0.04,
      },
    {
        menuId: 4,
        menuName: '짬뽕',
        menuCalorie: 1.5,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '4 짬뽕.jpg')).toString('base64'),
        menuCarbo: 0.26,
        menuProtein: 0.06,
        menuFat: 0.024,
      },
      {
        menuId: 5,
        menuName: '후라이드 치킨',
        menuCalorie: 2.8,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '5 후라이드 치킨.jpg')).toString('base64'),
        menuCarbo: 0.1,
        menuProtein: 0.24,
        menuFat: 0.22,
      },
      {
        menuId: 6,
        menuName: '피자',
        menuCalorie: 2.6,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '6 피자.jpg')).toString('base64'),
        menuCarbo: 0.27,
        menuProtein: 0.09,
        menuFat: 0.1,
      },
      {
        menuId: 7,
        menuName: '마라탕',
        menuCalorie: 0.9,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '7 마라탕.jpg')).toString('base64'),
        menuCarbo: 0.046,
        menuProtein: 0.04,
        menuFat: 0.036,
      },
      {
        menuId: 8,
        menuName: '족발',
        menuCalorie: 2.3,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '8 족발.jpg')).toString('base64'),
        menuCarbo: 0.003,
        menuProtein: 0.2,
        menuFat: 0.16,
      },
      {
        menuId: 9,
        menuName: '보쌈',
        menuCalorie: 2.9,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '9 보쌈.jpg')).toString('base64'),
        menuCarbo: 0.011,
        menuProtein: 0.14,
        menuFat: 0.25,
      },
      {
        menuId: 10,
        menuName: '돈까스',
        menuCalorie: 2.8,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '10 돈까스.jpg')).toString('base64'),
        menuCarbo: 0.1,
        menuProtein: 0.2,
        menuFat: 0.15,
      },
      {
        menuId: 11,
        menuName: '그릭 요거트',
        menuCalorie: 1.7,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '11 그릭 요거트.jpg')).toString('base64'),
        menuCarbo: 0.05,
        menuProtein: 0.11,
        menuFat: 0.09,
      },
      {
        menuId: 12,
        menuName: '김치찌개',
        menuCalorie: 0.6,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '12 김치찌개.jpg')).toString('base64'),
        menuCarbo: 0.025,
        menuProtein: 0.04,
        menuFat: 0.04,
      },
      {
        menuId: 13,
        menuName: '된장찌개',
        menuCalorie: 0.46,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '13 된장찌개.jpg')).toString('base64'),
        menuCarbo: 0.03,
        menuProtein: 0.035,
        menuFat: 0.017,
      },
      {
        menuId: 14,
        menuName: '물냉면',
        menuCalorie: 1,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '14 물냉면.jpg')).toString('base64'),
        menuCarbo: 0.15,
        menuProtein: 0.04,
        menuFat: 0.014,
      },
      {
        menuId: 15,
        menuName: '햄버거',
        menuCalorie: 2.9,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '15 햄버거.jpg')).toString('base64'),
        menuCarbo: 0.27,
        menuProtein: 0.16,
        menuFat: 0.12,
      },
      {
        menuId: 16,
        menuName: '떡볶이',
        menuCalorie: 2.9,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '16 떡볶이.jpg')).toString('base64'),
        menuCarbo: 0.27,
        menuProtein: 0.035,
        menuFat: 0.015,
      },
      {
        menuId: 17,
        menuName: '삶은계란',
        menuCalorie: 1.56,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '17 삶은계란.jpg')).toString('base64'),
        menuCarbo: 0.012,
        menuProtein: 0.126,
        menuFat: 0.106,
      },
      {
        menuId: 18,
        menuName: '사과',
        menuCalorie: 0.57,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '18 사과.jpg')).toString('base64'),
        menuCarbo: 0.114,
        menuProtein: 0.003,
        menuFat: 0.002,
      },
      {
        menuId: 19,
        menuName: '현미밥',
        menuCalorie: 1.53,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '19 현미밥.jpg')).toString('base64'),
        menuCarbo: 0.32,
        menuProtein: 0.03,
        menuFat: 0.007,
      },
      {
        menuId: 20,
        menuName: '돼지국밥',
        menuCalorie: 1.53,
        menuImage: fs.readFileSync(path.join(__dirname, 'images', '20 돼지국밥.jpg')).toString('base64'),
        menuCarbo: 0.11,
        menuProtein: 0.138,
        menuFat: 0.052,
      },
      {
        menuId: 21,
        menuName: '삼겹살',
        menuCalorie: 3.3,
        menuCarbo: 0.006,
        menuProtein: 0.173,
        menuFat: 0.28,
      }
  ]);
  console.log('MenuList added');
};

module.exports = menuData;
